import React from 'react'
import {
    Tabs,
    TabList,
    TabPanels,
    Tab,
    TabPanel,
    Box,
    Center,
    Container,
    Text,
    Heading,
    Button,
} from '@chakra-ui/react';
import CarbonChart from './CarbonChart';
import UsageBar from './UsageBar';
import Report from './Report';


function AnalyticsTab() {
    return (
        <Tabs isFitted variant='enclosed'>
            <TabList mb='1em'>
                <Tab>Carbon Footprint</Tab>
                <Tab>Energy Usage</Tab>
                <Tab>Energy Efficiency</Tab>
                <Tab>Report</Tab>
            </TabList>
            <TabPanels>
                <TabPanel>
                    <Container maxWidth={1600} mt={2} centerContent>
                        <Heading pb={5}>Carbon Footprint</Heading>
                        <Text pb={10}>This is your carbon footprint. Carbon footprint is the total amount of greenhouse gases 
                            (including carbon dioxide and methane) that are generated by our actions.</Text>
                        <CarbonChart />
                    </Container>
                </TabPanel>
                <TabPanel>
                    <Container maxWidth={1600} mt={2} centerContent>
                        <UsageBar />
                    </Container>
                </TabPanel>
                <TabPanel>
                    <p>Efficiency</p>
                </TabPanel>
                <TabPanel>
                <Container>
                        <Report />
                    </Container>
                </TabPanel>
            </TabPanels>
        </Tabs>
    )
}

export default AnalyticsTab