import React from 'react'
import Chart from "chart.js/auto";
import {
  Tabs,
  TabList,
  TabPanels,
  Tab,
  TabPanel,
  Box,
  Center,
  Container,
  Text,
  Heading
} from '@chakra-ui/react';
import { Line } from "react-chartjs-2";
import { getByPlaceholderText } from '@testing-library/react';


const labels = ["January", "February", "March", "April", "May", "June"];

const data = {
  labels: labels,
  datasets: [
    {
      label: "My First dataset",
      backgroundColor: "rgb(255, 99, 132)",
      borderColor: "rgb(255, 99, 132)",
      data: [0, 10, 5, 2, 20, 30, 45],
    },
    {
      label: "My Second dataset",
      backgroundColor: "rgb(124,252,0)",
      borderColor: "rgb(124,252,0)",
      data: [2, 4, 6, 10, 34, 60],
    },
  ],
};

const options = {
  legend:{
    labels:{
      font:{
        size:30,
      }
    }
  },
  scales: {
      x: {
          beginAtZero: true,
          title:{
              display: true,
              text: "Month",
              font:{
                size: 30,
                weight: "bold",
              }
          },
          ticks: {
              font: {
                  size: 30,
              },
          },
      },
      y:{
        beginAtZero: true,
        title:{
          display: true,
          text: "Carbon Footprint",
          font:{
            size: 30,
            weight: "bold",
          }
      },
        ticks: {
          font: {
              size: 30,
          }
      }
      },

  }
};



function CarbonChart() {

  return (
    <Container maxWidth={1600} mt={2} centerContent>
        <Heading pb={5}>Carbon Footprint</Heading>
        <Text pb={10}>This is your carbon footprint. Carbon footprint is the total amount of greenhouse gases 
            (including carbon dioxide and methane) that are generated by our actions.</Text>
            <Line options={options} data={data} />
    </Container>

    
  )
}

export default CarbonChart